#!/bin/bash

#   ImmuSeeker
#
#   Authors:    Limin Jiang (lxj423@med.miami.edu)
#   Date:       June 1, 2024
#   Version:    0.1.0
# Default values

#######################################Help#########################################

display_help() {
  echo "Usage: ImmuSeeker [-HLA | -KIR] [-SwithB | -SwithF] -i <Parameter1> -v <Parameter2> -c <Parameter3> -n <Parameter4>  -p <Parameter5> -p1 <Parameter6> -o <Parameter7>  -er <Parameter8> -ex <Parameter9> -pt <Parameter10> -dv <Parameter11> -nr <Parameter12>"
  echo "Options:"
  echo "  -HLA     Invoke the HLA calling process."
  echo "  -KIR     Invoke the KIR calling process."
  echo "  -SwithB  Input alignment BAM file."
  echo "  -SwithF  Input FASTQ file."
  echo "  -i       Set the input directory and filename. Example: 'your/input/directory/inputfile.bam'."
  echo "  -v       Input parameter or file name. 
	   If using -SwithB, specify the genome version with '-v hg37' or '-v hg38'. 
	   If using -SwithF, specify FASTQ file(s) with '-i file1,file2' (two files) or '-i file' (one file)."
  echo "  -c       Specify min number of supported unique reads (default: 5)."  
  echo "  -n       Max mismatches in seed (default: 0)."
  echo "  -p       Set a noninformative flat prior to allow the data to have a strong influence on the posterior distribution. (default: -p '(1/3,1/3,1/3)')."
  echo "  -p1      Set the probability of observing an allele in genotype (default: 1/2)."
  echo "  -o       Set the output directory and filename. Example: 'your/output/directory/outfile'."
  echo "  -ex      Specify whether to output gene expression values(default: -ex false)."
  echo "  -pt      Specify whether to output phylogenetic tree for HLAs (default: false)."
  echo "  -dv      Specify whether to output diversity analysis results based on the number of unique reads ('dvr') or gene expression ('dve'). (default:  false)."
  echo "  -nr      Specify the type of reads to account for when calculating gene expression. Choose between HLA reads ('HLAn') or total reads ('Totaln'). Calculating using total reads requires more time. (default: 'HLAn')."
  echo "  -er      Specify the sequencing error ratio (default: 0.02)."
  echo "  --help   Display this help message."
  exit 0
}


#######################################predefine#########################################
HLA="false"
KIR="false"
swithB="false"
swithF="false"
param_ex="false"
param_pt="false"
param_dv="false"
param_v=""
param_i=""
param_o=""
param_er=0.02
param_c=5
param_p="(1/3,1/3,1/3)"
param_p1=0.5
param_n=0
param_nr="HLAn"


#######################################Process command line options#######################

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    -HLA)
      HLA="true"
      ;;
    -KIR)
      KIR="true"
      ;;
    -SwithB)
      swithB="true"
      ;;
    -SwithF)
      swithF="true"
      ;;
    -i)
      param_i="$2" #"/ImmuSeeker_data/$2"
      shift
      ;;
    -v)
      param_v="$2"
      shift
      ;;
    -o)
      param_o="$2" #"/ImmuSeeker_data/$2"
      shift
      ;;
    -ex)
      param_ex="$2"
	  shift
      ;;
	-pt)
	  param_pt="$2"
	  shift
	  ;;
	-dv)
	  param_dv="$2"
	  shift
	  ;;
	-er)
      param_er="$2"
      shift
      ;;
	-c)
      param_c="$2"
      shift
      ;;
	-p)
      param_p="$2"
      shift
      ;;
    -p1)
      param_p1="$2"
      shift
      ;;
    -n)
      param_n="$2"
      shift
      ;;
	-nr)
      param_nr="$2"
      shift
      ;;
    --help)
      display_help
      ;;
    *)
      echo "Invalid option: $1" >&2
      display_help
      ;;
  esac
  shift
done

# Validate options
if [[ ($HLA != "true" && $KIR != "true") || ($HLA == "true" && $KIR == "true") ]]; then
  echo "Error: Please provide either -HLA or -KIR"
  display_help
fi


if [[ ($swithB != "true" && $swithF != "true")  || ($swithB == "true" && $swithF == "true")  ]]; then
  echo "Error: Please provide either -SwithB or -SwithF."
  display_help
fi



if [[ -z $param_i ]]; then
  echo "Error: Please Ensure that both -i options are included."
  display_help
fi

if [[ -z $param_o ]]; then
  echo "Warning: The output file name is ${param_i}_output!"
  param_o="$param_i""_output"
  #display_help
fi

if [[ $param_ex == "false" && $param_dv == "dve" ]]; then
	echo "Warning: Diversity analysis cannot be executed because the gene expression value was not provided. 
	We have corrected your -ex option to true in your command.
	If you wish to save time, please use the -dv 'dvr' option to perform diversity analysis based on the number of unique reads."
	param_ex="true"
    #display_help
fi


if [[ "$param_dv" != "false" && "$param_dv" != "dve" && "$param_dv" != "dvr" ]]; then
  echo "Error: The value of -dv is not in the allowed set ('false', 'dve', 'dvr')."
  display_help
  
fi


echo "HLA: $HLA"
echo "KIR: $KIR"
echo "SwithB: $swithB"
echo "SwithF: $swithF"
echo "Parameter 1 (-i): $param_i" 
echo "Parameter 2 (-o): $param_o" 
echo "Parameter 3 (-ex): $param_ex"
echo "Parameter 4 (-v): $param_v"
echo "Parameter 5 (-er): $param_er"
echo "Parameter 6 (-c): $param_c"
echo "Parameter 7 (-p): $param_p"
echo "Parameter 8 (-p1): $param_p1"
echo "Parameter 9 (-n): $param_n"
echo "Parameter 10 (-pt): $param_pt"
echo "Parameter 11 (-dv): $param_dv"
echo "Parameter 12 (-nr): $param_nr"

#######################################software########################################


if [[ "$HLA" == "true" ]]; then
	echo ".............run HLA.........."
	parameters=(
		"$swithB"
		"$swithF"
		"$param_i"
		"$param_o"
		"$param_ex"		
		"$param_v"
		"$param_er"
		"$param_c"		
		"$param_p"
		"$param_p1"
		"$param_n"
		"$param_pt"
		"$param_dv"
		"param_nr"
	)
  . code/HLAdetector "${parameters[@]}"
fi

if [[ "$KIR" == "true" ]]; then
	echo ".............run KIR.........."
	parameters=(
		"$swithB"
		"$swithF"
		"$param_i"
		"$param_o"
		"$param_ex"		
		"$param_v"
		"$param_er"
		"$param_c"		
		"$param_p"
		"$param_p1"
		"$param_n"
		"$param_pt"
		"$param_dv"
		"param_nr"
	)
  . code/KIRdetector "${parameters[@]}"
fi



